title: Nanfei's Homepage
page-top-title: Nanfei
top-section-bg-text: The last generation before AGI dawn.
home-subtitle: Ye Nanfei&ensp;|&ensp;叶南飞
copyright-text: '&copy; Nanfei 2025- . All Rights Reserved.'
